//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalOdevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public string adi { get; set; }
        public string tur { get; set; }
        public string konumu { get; set; }
        public string sorumlu { get; set; }
        public string durumu { get; set; }
        public string tarih { get; set; }
        public string diger { get; set; }
        public int id { get; set; }
    }
}
