//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalOdevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
        public string isim { get; set; }
        public string telefon { get; set; }
        public string eposta { get; set; }
        public string seviye { get; set; }
        public int id { get; set; }
    }
}
